name: Destroy Zomato Infra

on:
  workflow_dispatch:
  # Optional: Uncomment if you want destroy to run on branch push (usually not recommended)
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'Terraform-Code/modules/**'
  #     - 'Terraform-Code/environments/**'
  #     - 'Terraform-Code/scripts/**'
  #     - '.github/workflows/**'

env:
  TF_VERSION: "1.6.6"
  TF_WORKING_DIR: "Terraform-Code/environments/dev"
  AWS_REGION: "ap-southeast-1"

jobs:
  destroy:
    name: Terraform Destroy Zomato Infra
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Destroy Plan
        run: terraform plan -destroy -out=tfplan_destroy -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Destroy Apply
        run: terraform apply -auto-approve tfplan_destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
